In [20]:
import pandas as pd
import matplotlib.pyplot as plt 
import numpy as np
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import SimpleImputer, KNNImputer , IterativeImputer
from scipy import stats

In [9]:
df = pd.read_csv('patient_health_500.csv')
df

,patient_id,age,gender,region,bmi,blood_pressure,cholesterol,glucose,disease_risk
0,1,NaN,NaN,NaN,NaN,118.00,NaN,NaN,0
1,2,69.0,Male,South,20.91,136.29,254.35,96.29,1
2,3,NaN,NaN,NaN,NaN,88.49,NaN,NaN,1
3,4,32.0,Male,South,27.01,164.07,175.13,64.69,1
4,5,60.0,Male,South,23.26,106.93,162.01,56.40,0
...,...,...,...,...,...,...,...,...,...
495,496,NaN,NaN,NaN,NaN,113.26,NaN,NaN,1
496,497,41.0,Female,West,22.06,135.26,232.26,106.71,0
497,498,NaN,NaN,NaN,NaN,159.95,NaN,NaN,1
498,499,49.0,Male,South,25.70,115.57,246.44,134.91,1
499,500,64.0,Male,North,27.26,122.28,177.16,110.37,0

In [10]:
df.isnull().sum()

patient_id         0
age               50
gender            50
region            50
bmi               50
blood_pressure     0
cholesterol       50
glucose           50
disease_risk       0
dtype: int64

In [11]:
(df.isnull().sum()/len(df))*100

patient_id         0.0
age               10.0
gender            10.0
region            10.0
bmi               10.0
blood_pressure     0.0
cholesterol       10.0
glucose           10.0
disease_risk       0.0
dtype: float64

In [12]:
simple_im  = SimpleImputer(strategy='mean')
df["bmi"] = simple_im.fit_transform(df[["bmi"]])
print(df)

     patient_id   age  gender region        bmi  blood_pressure  cholesterol  \
0             1   NaN     NaN    NaN  25.536547          118.00          NaN
1             2  69.0    Male  South  20.910000          136.29       254.35
2             3   NaN     NaN    NaN  25.536547           88.49          NaN
3             4  32.0    Male  South  27.010000          164.07       175.13
4             5  60.0    Male  South  23.260000          106.93       162.01
..          ...   ...     ...    ...        ...             ...          ...
495         496   NaN     NaN    NaN  25.536547          113.26          NaN
496         497  41.0  Female   West  22.060000          135.26       232.26
497         498   NaN     NaN    NaN  25.536547          159.95          NaN
498         499  49.0    Male  South  25.700000          115.57       246.44
499         500  64.0    Male  North  27.260000          122.28       177.16

     glucose  disease_risk
0        NaN             0
1      96.29             1
2        NaN             1
3      64.69             1
4      56.40             0
..       ...           ...
495      NaN             1
496   106.71             0
497      NaN             1
498   134.91             1
499   110.37             0

[500 rows x 9 columns]

In [13]:
imputer_mf = SimpleImputer(strategy='most_frequent')
df["region"] = imputer_mf.fit_transform(df[["region"]]).ravel()
print(df)

     patient_id   age  gender region        bmi  blood_pressure  cholesterol  \
0             1   NaN     NaN  South  25.536547          118.00          NaN
1             2  69.0    Male  South  20.910000          136.29       254.35
2             3   NaN     NaN  South  25.536547           88.49          NaN
3             4  32.0    Male  South  27.010000          164.07       175.13
4             5  60.0    Male  South  23.260000          106.93       162.01
..          ...   ...     ...    ...        ...             ...          ...
495         496   NaN     NaN  South  25.536547          113.26          NaN
496         497  41.0  Female   West  22.060000          135.26       232.26
497         498   NaN     NaN  South  25.536547          159.95          NaN
498         499  49.0    Male  South  25.700000          115.57       246.44
499         500  64.0    Male  North  27.260000          122.28       177.16

     glucose  disease_risk
0        NaN             0
1      96.29             1
2        NaN             1
3      64.69             1
4      56.40             0
..       ...           ...
495      NaN             1
496   106.71             0
497      NaN             1
498   134.91             1
499   110.37             0

[500 rows x 9 columns]

In [14]:
imputer_mf1 = SimpleImputer(strategy='most_frequent')
df['gender'] = imputer_mf1.fit_transform(df[["gender"]]).ravel()
print(df)

     patient_id   age  gender region        bmi  blood_pressure  cholesterol  \
0             1   NaN  Female  South  25.536547          118.00          NaN
1             2  69.0    Male  South  20.910000          136.29       254.35
2             3   NaN  Female  South  25.536547           88.49          NaN
3             4  32.0    Male  South  27.010000          164.07       175.13
4             5  60.0    Male  South  23.260000          106.93       162.01
..          ...   ...     ...    ...        ...             ...          ...
495         496   NaN  Female  South  25.536547          113.26          NaN
496         497  41.0  Female   West  22.060000          135.26       232.26
497         498   NaN  Female  South  25.536547          159.95          NaN
498         499  49.0    Male  South  25.700000          115.57       246.44
499         500  64.0    Male  North  27.260000          122.28       177.16

     glucose  disease_risk
0        NaN             0
1      96.29             1
2        NaN             1
3      64.69             1
4      56.40             0
..       ...           ...
495      NaN             1
496   106.71             0
497      NaN             1
498   134.91             1
499   110.37             0

[500 rows x 9 columns]

In [15]:
columns = ["age", "bmi", "blood_pressure", "cholesterol", "glucose"]

In [16]:
for col in columns:
    df[col + '_missing'] = df[col].isnull().astype(int)
    missing_val = df[col].isnull().sum()
    if missing_val > 0:
        random_sample = df[col].dropna().sample(missing_val, random_state=42) 
        random_sample.index = df[df[col].isnull()].index
        df.loc[df[col].isnull(), col] = random_sample

In [17]:
knn = KNNImputer(n_neighbors=5)

df[columns] = knn.fit_transform(df[columns])
print(df)

     patient_id   age  gender region        bmi  blood_pressure  cholesterol  \
0             1  64.0  Female  South  25.536547          118.00       233.77
1             2  69.0    Male  South  20.910000          136.29       254.35
2             3  75.0  Female  South  25.536547           88.49       177.74
3             4  32.0    Male  South  27.010000          164.07       175.13
4             5  60.0    Male  South  23.260000          106.93       162.01
..          ...   ...     ...    ...        ...             ...          ...
495         496  68.0  Female  South  25.536547          113.26       226.70
496         497  41.0  Female   West  22.060000          135.26       232.26
497         498  71.0  Female  South  25.536547          159.95       180.12
498         499  49.0    Male  South  25.700000          115.57       246.44
499         500  64.0    Male  North  27.260000          122.28       177.16

     glucose  disease_risk  age_missing  bmi_missing  blood_pressure_missing  \
0      67.89             0            1            0                       0
1      96.29             1            0            0                       0
2     132.23             1            1            0                       0
3      64.69             1            0            0                       0
4      56.40             0            0            0                       0
..       ...           ...          ...          ...                     ...
495    93.97             1            1            0                       0
496   106.71             0            0            0                       0
497    97.88             1            1            0                       0
498   134.91             1            0            0                       0
499   110.37             0            0            0                       0

     cholesterol_missing  glucose_missing
0                      1                1
1                      0                0
2                      1                1
3                      0                0
4                      0                0
..                   ...              ...
495                    1                1
496                    0                0
497                    1                1
498                    0                0
499                    0                0

[500 rows x 14 columns]

In [18]:
mice_imputer = IterativeImputer(random_state=0)

df[columns] = mice_imputer.fit_transform(df[columns])

df.isnull().sum()

patient_id                0
age                       0
gender                    0
region                    0
bmi                       0
blood_pressure            0
cholesterol               0
glucose                   0
disease_risk              0
age_missing               0
bmi_missing               0
blood_pressure_missing    0
cholesterol_missing       0
glucose_missing           0
dtype: int64

In [23]:
z_scores = np.abs(stats.zscore(df[["cholesterol", "glucose"]]))

outliers = (z_scores > 3).any(axis=1)

In [24]:
print((outliers).sum())

10

In [25]:
extreme_patients = df[(z_scores > 3).any(axis=1)]

extreme_patients

,patient_id,age,gender,region,bmi,blood_pressure,cholesterol,glucose,disease_risk,age_missing,bmi_missing,blood_pressure_missing,cholesterol_missing,glucose_missing
106,107,32.0,Male,South,39.078,137.24,235.84,231.44,0,0,0,0,0,0
158,159,51.0,Female,South,50.472,116.09,222.03,263.28,0,0,0,0,0,0
228,229,47.0,Female,East,27.594,128.10,204.35,238.70,0,0,0,0,0,0
260,261,76.0,Female,North,49.896,132.95,255.21,290.66,1,0,0,0,0,0
305,306,28.0,Female,North,32.850,113.46,227.12,213.84,0,0,0,0,0,0
414,415,50.0,Female,South,46.026,134.22,191.65,205.60,0,0,0,0,0,0
423,424,24.0,Male,North,40.230,99.52,210.05,230.00,0,0,0,0,0,0
453,454,78.0,Female,West,38.826,117.59,185.35,212.98,0,0,0,0,0,0
456,457,21.0,Female,South,30.150,125.32,195.21,301.44,1,0,0,0,0,0
483,484,49.0,Male,East,44.190,106.21,190.40,267.30,0,0,0,0,0,0

In [26]:
Q1 = df["bmi"].quantile(0.25)
Q3 = df["bmi"].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

print("Lower: ", lower)
print("Upper: ", upper)

Lower:  13.068750000000001
Upper:  37.25875

In [27]:
outliers_IQR = df[(df["bmi"] < lower) | (df["bmi"] > upper)]

outliers_IQR

,patient_id,age,gender,region,bmi,blood_pressure,cholesterol,glucose,disease_risk,age_missing,bmi_missing,blood_pressure_missing,cholesterol_missing,glucose_missing
23,24,41.0,Female,East,38.220,130.03,202.85,104.81,1,0,0,0,0,0
38,39,44.0,Female,North,37.690,130.82,145.08,141.79,1,0,0,0,0,0
72,73,37.0,Female,South,37.850,117.17,200.98,121.04,1,0,0,0,0,0
75,76,77.0,Male,South,11.700,105.74,206.72,52.64,0,0,0,0,0,0
106,107,32.0,Male,South,39.078,137.24,235.84,231.44,0,0,0,0,0,0
134,135,26.0,Male,South,40.770,98.47,193.34,123.68,0,0,0,0,0,0
158,159,51.0,Female,South,50.472,116.09,222.03,263.28,0,0,0,0,0,0
217,218,59.0,Female,East,12.580,120.96,232.28,123.44,0,0,0,0,0,0
251,252,26.0,Female,East,41.616,102.43,180.63,144.92,0,0,0,0,0,0
253,254,54.0,Male,West,38.664,115.25,185.43,124.24,0,0,0,0,0,0
260,261,76.0,Female,North,49.896,132.95,255.21,290.66,1,0,0,0,0,0
261,262,71.0,Female,North,54.756,108.05,177.64,167.12,1,0,0,0,0,0
272,273,29.0,Male,West,7.600,85.46,247.57,92.64,1,0,0,0,0,0
318,319,33.0,Male,East,41.742,111.25,162.16,156.78,0,0,0,0,0,0
363,364,77.0,Male,West,49.428,121.18,193.87,98.22,0,0,0,0,0,0
366,367,18.0,Female,East,48.366,124.93,270.00,176.04,1,0,0,0,0,0
380,381,33.0,Female,North,37.360,112.28,215.45,103.39,1,0,0,0,0,0
414,415,50.0,Female,South,46.026,134.22,191.65,205.60,0,0,0,0,0,0
423,424,24.0,Male,North,40.230,99.52,210.05,230.00,0,0,0,0,0,0
426,427,50.0,Female,South,39.830,147.93,265.62,81.58,1,0,0,0,0,0
453,454,78.0,Female,West,38.826,117.59,185.35,212.98,0,0,0,0,0,0
483,484,49.0,Male,East,44.190,106.21,190.40,267.30,0,0,0,0,0,0

In [29]:
for col in columns:
  lower= df[col].quantile(0.01)
  upper= df[col].quantile(0.99)

In [30]:
df = (df[col] >= lower) & (df[col] <= upper)

In [31]:
df.shape[0]

500

## PART C — Final Clean Dataset

In [32]:
print(df.isnull().sum())

0

In [33]:
df.shape[0]

500

In [34]:
df.describe()

count      500
unique       2
top       True
freq       490
Name: glucose, dtype: object

In [36]:
df.to_csv("final_data.csv", index=False)

In [39]:
before_df = pd.read_csv("patient_health_500.csv")

print("Original ", before_df.shape)
print("Cleaned ", df.shape)

Original  (500, 9)
Cleaned  (500,)

In [40]:
print("Before Cleaning:\n", before_df.describe())
print("\nAfter Cleaning:\n", df.describe())

Before Cleaning:
        patient_id         age         bmi  blood_pressure  cholesterol  \
count  500.000000  450.000000  450.000000      500.000000   450.000000
mean   250.500000   49.948889   25.536547      119.722760   200.481400
std    144.481833   18.233808    6.065450       14.902468    29.430711
min      1.000000   18.000000    7.600000       76.680000   115.020000
25%    125.750000   35.000000   21.657500      109.047500   180.522500
50%    250.500000   50.000000   25.240000      120.345000   200.795000
75%    375.250000   65.750000   28.770000      129.452500   221.822500
max    500.000000   79.000000   54.756000      164.070000   281.930000

          glucose  disease_risk
count  450.000000    500.000000
mean   102.957689      0.314000
std     33.318458      0.464581
min     13.210000      0.000000
25%     82.625000      0.000000
50%    100.975000      0.000000
75%    119.427500      1.000000
max    301.440000      1.000000

After Cleaning:
 count      500
unique       2
top       True
freq       490
Name: glucose, dtype: object